common:
  DiskIndex:
    BeamWidthRatio: 4
    BuildNumThreadsRatio: 1
    LoadNumThreadRatio: 8
    MaxDegree: 56
    PQCodeBudgetGBRatio: 0.125
    SearchCacheBudgetGBRatio: 0.1
    SearchListSize: 100
  chanNamePrefix:
    cluster: by-dev
    cmd: cmd
    dataCoordSegmentInfo: segment-info-channel
    dataCoordStatistic: datacoord-statistics-channel
    dataCoordTimeTick: datacoord-timetick-channel
    queryNodeStats: query-node-stats
    queryTimeTick: queryTimeTick
    rootCoordDelta: rootcoord-delta
    rootCoordDml: rootcoord-dml
    rootCoordStatistics: rootcoord-statistics
    rootCoordTimeTick: rootcoord-timetick
    search: search
    searchResult: searchResult
  defaultIndexName: _default_idx
  defaultPartitionName: _default
  entityExpiration: -1
  gracefulStopTimeout: 30
  gracefulTime: 5000
  indexSliceSize: 16
  retentionDuration: 0
  security:
    authorizationEnabled: false
    tlsMode: 0
  session:
    retryTimes: 30
    ttl: 60
  simdType: auto
  storageType: minio
  subNamePrefix:
    dataCoordSubNamePrefix: dataCoord
    dataNodeSubNamePrefix: dataNode
    proxySubNamePrefix: proxy
    queryNodeSubNamePrefix: queryNode
    rootCoordSubNamePrefix: rootCoord
  threadCoreCoefficient: 10
dataCoord:
  address: localhost
  channel:
    maxWatchDuration: 600
  compaction:
    enableAutoCompaction: true
  enableActiveStandby: false
  enableCompaction: true
  enableGarbageCollection: true
  gc:
    dropTolerance: 3600
    interval: 3600
    missingTolerance: 86400
  port: 13333
  segment:
    assignmentExpiration: 2000
    compactableProportion: 0.85
    diskSegmentMaxSize: 2048
    maxBinlogFileNumber: 32
    maxIdleTime: 600
    maxLife: 86400
    maxSize: 512
    minSizeFromIdleToSealed: 16
    sealProportion: 0.23
    smallProportion: 0.5
dataNode:
  dataSync:
    flowGraph:
      maxParallelism: 1024
      maxQueueLength: 1024
  port: 21124
  segment:
    deleteBufBytes: 67108864
    insertBufSize: 16777216
    syncPeriod: 600
etcd:
  data:
    dir: default.etcd
  endpoints:
  - my-release-etcd.default:2379
  kvSubPath: kv
  log:
    level: info
    path: stdout
  metaSubPath: meta
  rootPath: my-release
  ssl:
    enabled: false
    tlsCACert: /path/to/ca.pem
    tlsCert: /path/to/etcd-client.pem
    tlsKey: /path/to/etcd-client-key.pem
    tlsMinVersion: 1.3
  use:
    embed: false
grpc:
  client:
    backoffMultiplier: 2
    dialTimeout: 5000
    initialBackOff: 1
    keepAliveTime: 10000
    keepAliveTimeout: 20000
    maxBackoff: 60
    maxMaxAttempts: 5
  clientMaxRecvSize: 104857600
  clientMaxSendSize: 104857600
  log:
    level: WARNING
  serverMaxRecvSize: 536870912
  serverMaxSendSize: 536870912
indexCoord:
  address: localhost
  bindIndexNodeMode:
    address: localhost:22930
    enable: false
    nodeID: 0
    withCred: false
  enableActiveStandby: false
  gc:
    interval: 600
  minSegmentNumRowsToEnableIndex: 1024
  port: 31000
  scheduler:
    interval: 1000
indexNode:
  enableDisk: true
  gracefulStopTimeout: 30
  maxDiskUsagePercentage: 95
  port: 21121
  scheduler:
    buildParallel: 1
localStorage:
  path: /var/lib/milvus/data/
log:
  file:
    maxAge: 10
    maxBackups: 20
    maxSize: 300
    rootPath: ""
  format: text
  level: debug
  stdout: "true"
messageQueue: rocksmq
metastore:
  type: etcd
minio:
  accessKeyID: minioadmin
  address: my-release-minio.default
  bucketName: my-release
  cloudProvider: aws
  iamEndpoint: ""
  port: 9000
  rootPath: files
  secretAccessKey: minioadmin
  useIAM: false
  useSSL: false
msgChannel:
  chanNamePrefix:
    cluster: my-release
mysql:
  address: localhost
  dbName: milvus_meta
  driverName: mysql
  maxIdleConns: 5
  maxOpenConns: 20
  password: 123456
  port: 3306
  username: root
proxy:
  ginLogging: true
  grpc:
    clientMaxRecvSize: 104857600
    clientMaxSendSize: 104857600
    serverMaxRecvSize: 67108864
    serverMaxSendSize: 67108864
  http:
    debug_mode: false
    enabled: true
  internalPort: 19529
  maxDimension: 32768
  maxFieldNum: 64
  maxNameLength: 255
  maxShardNum: 64
  maxTaskNum: 1024
  msgStream:
    timeTick:
      bufSize: 512
  port: 19530
  timeTickInterval: 200
queryCoord:
  address: localhost
  autoBalance: true
  autoHandoff: true
  balanceIntervalSeconds: 60
  channelTaskTimeout: 60000
  checkHandoffInterval: 5000
  checkInterval: 1000
  distPullInterval: 500
  enableActiveStandby: false
  loadTimeoutSeconds: 600
  memoryUsageMaxDifferencePercentage: 30
  overloadedMemoryThresholdPercentage: 90
  port: 19531
  refreshTargetsIntervalSeconds: 300
  segmentTaskTimeout: 120000
  taskExecutionCap: 256
  taskMergeCap: 16
queryNode:
  cache:
    enabled: true
    memoryLimit: 2147483648
  cacheSize: 32
  dataSync:
    flowGraph:
      maxParallelism: 1024
      maxQueueLength: 1024
  enableDisk: true
  gracefulStopTimeout: 30
  grouping:
    enabled: true
    maxNQ: 1000
    topKMergeRatio: 10
  loadMemoryUsageFactor: 3
  maxDiskUsagePercentage: 95
  port: 21123
  scheduler:
    cpuRatio: 10
    maxReadConcurrentRatio: 2
    maxTimestampLag: 86400
    receiveChanSize: 10240
    unsolvedQueueSize: 10240
  segcore:
    chunkRows: 1024
    smallIndex:
      nlist: 128
      nprobe: 16
  stats:
    publishInterval: 1000
quotaAndLimits:
  compactionRate:
    enabled: false
    max: -1
  ddl:
    collectionRate: -1
    enabled: false
    partitionRate: -1
  dml:
    bulkLoadRate:
      max: -1
    deleteRate:
      max: -1
    enabled: false
    insertRate:
      max: -1
  dql:
    enabled: false
    queryRate:
      max: -1
    searchRate:
      max: -1
  enabled: true
  flushRate:
    enabled: false
    max: -1
  indexRate:
    enabled: false
    max: -1
  limitReading:
    coolOffSpeed: 0.9
    forceDeny: false
    queueProtection:
      enabled: false
      nqInQueueThreshold: -1
      queueLatencyThreshold: -1
    resultProtection:
      enabled: false
      maxReadResultRate: -1
  limitWriting:
    diskProtection:
      diskQuota: -1
      enabled: true
    forceDeny: false
    memProtection:
      dataNodeMemoryHighWaterLevel: 0.95
      dataNodeMemoryLowWaterLevel: 0.85
      enabled: true
      queryNodeMemoryHighWaterLevel: 0.95
      queryNodeMemoryLowWaterLevel: 0.85
    ttProtection:
      enabled: false
      maxTimeTickDelay: 300
  quotaCenterCollectInterval: 3
rocksmq:
  compactionInterval: 86400
  lrucacheratio: 0.06
  path: /var/lib/milvus/rdb_data
  retentionSizeInMB: 8192
  retentionTimeInMinutes: 7200
  rocksmqPageSize: 2147483648
rootCoord:
  address: localhost
  dmlChannelNum: 256
  enableActiveStandby: false
  importTaskExpiration: 900
  importTaskRetention: 86400
  maxPartitionNum: 4096
  minSegmentSizeToEnableIndex: 1024
  port: 53100
tls:
  caPemPath: configs/cert/ca.pem
  serverKeyPath: configs/cert/server.key
  serverPemPath: configs/cert/server.pem