apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-cluster-pulsar-43
  # namespace: milvus
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    dataCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    queryCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    indexCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    rootCoord:
      resources:
        limits:
          cpu: 1
          memory: 2Gi
    dataNode:
      replicas: 1
      resources:
        limits:
          cpu: 2
          memory: 8Gi
    indexNode:
      replicas: 2
      resources:
        limits:
          cpu: 4
          memory: 8Gi
    queryNode:
      replicas: 3
      resources:
        limits:
          cpu: 4
          memory: 16Gi
    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 4Gi
  config: {}
  dependencies:
    etcd:
      inCluster:
        values:
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          extraEnvVars:
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
            - name: ETCD_HEARTBEAT_INTERVAL
              value: "500"
            - name: ETCD_ELECTION_TIMEOUT
              value: "25000"
            - name: ETCD_SNAPSHOT_COUNT
              value: "10000"
            - name: ETCD_ENABLE_PPROF
              value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi #SSD Required
            storageClass:
          replicaCount: 3
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 0
              memory: 0

    pulsar:
      inCluster:
        values:
          proxy:
            replicaCount: 2
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms2048M
                -Xmx2048M
                -XX:MaxDirectMemorySize=2048M
              httpNumThreads: "100"
          zookeeper:
            volumes:
              persistence: true
              data:
                name: data
                size: 20Gi #SSD Required
                storageClassName:
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
          bookkeeper:
            volumes:
              journal:
                name: journal
                size: 10Gi
                storageClassName:
              ledgers:
                name: ledgers
                size: 30Gi #SSD Required
                storageClassName:
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
                -XX:MaxDirectMemorySize=256m
          broker:
            component: broker
            podMonitor:
              enabled: false
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
    storage:
      inCluster:
        values:
          mode: distributed
          resources:
            limits:
              cpu: 2
              memory: 8Gi
          persistence:
            storageClass:
            accessMode: ReadWriteOnce
            size: 90Gi
