apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-cluster-pulsar-43
  # namespace: milvus
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    dataCoord:
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
    queryCoord:
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
    indexCoord:
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
    rootCoord:
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
    dataNode:
      replicas: 1
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
    indexNode:
      replicas: 2
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
    queryNode:
      replicas: 3
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
    proxy:
      replicas: 1
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
  config: {}
  dependencies:
    etcd:
      inCluster:
        values:
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          extraEnvVars:
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
            - name: ETCD_HEARTBEAT_INTERVAL
              value: "500"
            - name: ETCD_ELECTION_TIMEOUT
              value: "25000"
            - name: ETCD_SNAPSHOT_COUNT
              value: "10000"
            - name: ETCD_ENABLE_PPROF
              value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi #SSD Required
            storageClass:
          replicaCount: 3
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 0
              memory: 0

    pulsar:
      inCluster:
        values:
          components: 
            autorecovery: true
            functions: false
            toolset: false
            pulsar_manager: false
          monitoring:
            prometheus: false
            grafana: false
            node_exporter: false
            alert_manager: false
          proxy:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m 
                -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
          bookkeeper:
            volumes:
              journal:
                name: journal
                size: 10Gi
                storageClassName:
              ledgers:
                name: ledgers
                size: 30Gi #SSD Required
                storageClassName:
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
                -XX:MaxDirectMemorySize=256m
              PULSAR_GC: >
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+UseG1GC -XX:MaxGCPauseMillis=10
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
                -XX:+PerfDisableSharedMem
                -XX:+PrintGCDetails
          zookeeper:
            volumes:
              persistence: true
              data:
                name: data
                size: 20Gi #SSD Required
                storageClassName:
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -Dcom.sun.management.jmxremote
                -Djute.maxbuffer=10485760
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC
                -XX:+PerfDisableSharedMem
                -Dzookeeper.forceSync=no
          broker:
            component: broker
            podMonitor:
              enabled: false
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
    storage:
      inCluster:
        values:
          mode: distributed
          resources:
            limits:
              cpu: 2
              memory: 8Gi
          persistence:
            storageClass:
            accessMode: ReadWriteOnce
            size: 90Gi
